"""Builds downloadable deployment packages for a vertical.

Takes the vertical's templates (Bicep, data generation scripts, docs)
and user-provided configuration (resource group, region) and
produces a zip file the user can download and run locally.
"""
import shutil
import tempfile
import zipfile
from pathlib import Path

from jinja2 import Environment, FileSystemLoader

from app.services.vertical_registry import Vertical


class PackageBuilder:
    def __init__(self, vertical: Vertical):
        self.vertical = vertical
        if vertical.root_path is None:
            raise ValueError(f"Vertical {vertical.id} has no root path")
        self.root = vertical.root_path

    def build(self, config: dict) -> Path:
        """Render templates with user config and return path to generated zip."""
        out_dir = Path(tempfile.mkdtemp(prefix=f"contoso-{self.vertical.id}-"))
        staging = out_dir / f"contoso-{self.vertical.id}"
        staging.mkdir()

        # Items in the vertical folder that should not ship to end users.
        # `data-gen` is a dev tool for regenerating Faker data — Phase B replaces
        # it with a Fabric notebook that runs in the customer's tenant.
        # `teardown.ps1` / `teardown.cmd` / `logs` are artifacts written by a
        # PRIOR deploy run in the dev workspace; bundling them stamps the new
        # package with the OLD deployment's RG name.
        EXCLUDED = {"vertical.yaml", "data-gen", "teardown.ps1", "teardown.cmd", "logs"}

        # Copy vertical assets
        for item in self.root.iterdir():
            if item.name in EXCLUDED:
                continue
            dest = staging / item.name
            if item.is_dir():
                shutil.copytree(item, dest)
            else:
                shutil.copy2(item, dest)

        # Render config file the deployment scripts will read
        self._write_config(staging, config)

        # Render README from template if one exists
        self._render_readme(staging, config)

        # Zip it up - files at zip root (no nested folder)
        zip_path = out_dir / f"contoso-{self.vertical.id}-deployment.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
            for path in staging.rglob("*"):
                if path.is_file():
                    zf.write(path, path.relative_to(staging))
        return zip_path

    def _write_config(self, staging: Path, config: dict):
        lines = [
            "# Generated by Fabric Data Estate Builder",
            f"VERTICAL={self.vertical.id}",
            f"RESOURCE_GROUP={config['resource_group']}",
            f"LOCATION={config['location']}",
            f"RESOURCE_PREFIX={config['resource_prefix']}",
            f"AUTO_RUN_INITIAL_LOAD={'true' if config.get('auto_run_initial_load') else 'false'}",
        ]
        (staging / "deployment.config").write_text("\n".join(lines) + "\n", encoding="utf-8")

    def _render_readme(self, staging: Path, config: dict):
        template_path = self.root / "README.md.j2"
        if not template_path.exists():
            return
        env = Environment(loader=FileSystemLoader(self.root))
        tpl = env.get_template("README.md.j2")
        rendered = tpl.render(vertical=self.vertical, config=config)
        (staging / "README.md").write_text(rendered, encoding="utf-8")
        # Remove the .j2 file from the package
        j2_in_staging = staging / "README.md.j2"
        if j2_in_staging.exists():
            j2_in_staging.unlink()
