#Requires -Version 7.0
<#
.SYNOPSIS
    Deploys the Contoso Retail data estate to Azure.

.DESCRIPTION
    Reads deployment.config (generated by the Contoso Data Estate Builder web app),
    creates the resource group, deploys Bicep templates, and populates synthetic data.

.PREREQUISITES
    - Azure CLI installed and authenticated (`az login`)
    - PowerShell 7+
    - Python 3.10+ (for data generation)
    - Contributor role on target subscription

.EXAMPLE
    .\deploy.ps1
#>

$ErrorActionPreference = "Stop"

Write-Host "Contoso Retail - Deployment" -ForegroundColor Cyan
Write-Host "============================" -ForegroundColor Cyan

# Load config
$configPath = Join-Path $PSScriptRoot "deployment.config"
if (-not (Test-Path $configPath)) {
    Write-Error "deployment.config not found. This package may be corrupt."
    exit 1
}

$config = @{}
Get-Content $configPath | ForEach-Object {
    if ($_ -match '^([A-Z_]+)=(.+)$') {
        $config[$matches[1]] = $matches[2]
    }
}

Write-Host ""
Write-Host "Configuration:" -ForegroundColor Yellow
$config.GetEnumerator() | ForEach-Object { Write-Host "  $($_.Key) = $($_.Value)" }
Write-Host ""

# Verify Azure CLI
Write-Host "Verifying Azure CLI authentication..." -ForegroundColor Yellow
$account = az account show --output json 2>$null | ConvertFrom-Json
if (-not $account) {
    Write-Error "Not logged into Azure CLI. Run 'az login' first."
    exit 1
}
Write-Host "  Signed in as: $($account.user.name)" -ForegroundColor Green
Write-Host "  Subscription: $($account.name) ($($account.id))" -ForegroundColor Green
Write-Host ""

# TODO: Create resource group
Write-Host "[TODO] Create resource group $($config.RESOURCE_GROUP) in $($config.LOCATION)" -ForegroundColor DarkGray

# TODO: Deploy Bicep
Write-Host "[TODO] Deploy infra/main.bicep" -ForegroundColor DarkGray

# TODO: Run data generation
Write-Host "[TODO] Generate and load synthetic data (scale: $($config.SCALE))" -ForegroundColor DarkGray

# TODO: Configure Fabric / Purview
Write-Host "[TODO] Configure Fabric workspace and Purview catalog" -ForegroundColor DarkGray

Write-Host ""
Write-Host "Deployment scaffold complete. Real deployment logic coming soon." -ForegroundColor Cyan
